project:
  type: website
  output-dir: docs 

website:
  title: "我的笔记"
  navbar:
    left:
      - href: index.qmd
        text: 主页
        menu:
          - text: 网站使用笔记
            menu:
              - text: 测试网站和网站用法
                href: notebooks/test.ipynb
          
          - text: 深度学习
            menu:
              - text: PyTorch 基础
                href: deep-learning/PyTorch.ipynb
                

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



